// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXz8UBBZO-QrectM_KG3RwpPY40YPMpE8',
    appId: '1:133152571072:web:81d3c77c06ba6fc2237725',
    messagingSenderId: '133152571072',
    projectId: 'medialert-2024',
    authDomain: 'medialert-2024.firebaseapp.com',
    storageBucket: 'medialert-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJMSC548cD577QjDduLZ82t8Ro3ST5uLU',
    appId: '1:334744837326:android:9d49c2d5c8d35ab315049f',
    messagingSenderId: '334744837326',
    projectId: 'pillscheduler',
    storageBucket: 'pillscheduler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5T2vqWNMHs3vg2mZ_XkQcgWvFStfk8jU',
    appId: '1:334744837326:ios:26fb9cb75042dc6415049f',
    messagingSenderId: '334744837326',
    projectId: 'pillscheduler',
    storageBucket: 'pillscheduler.firebasestorage.app',
    iosClientId: '334744837326-1mm11g4qor3m2vju3r36c044209ghfok.apps.googleusercontent.com',
    iosBundleId: 'com.zerobee.pillscheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_QAuu5HFUCXGG-Lq9fjWfHEwV53MZVTw',
    appId: '1:133152571072:ios:4b041c911db7f0ea237725',
    messagingSenderId: '133152571072',
    projectId: 'medialert-2024',
    storageBucket: 'medialert-2024.firebasestorage.app',
    androidClientId: '133152571072-q2rgt4pola98pbb6l8r67fj9q2t64hc7.apps.googleusercontent.com',
    iosClientId: '133152571072-r0f76deflh47ekbl1tbel0eavloot0o6.apps.googleusercontent.com',
    iosBundleId: 'com.zerobee.pillscheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXz8UBBZO-QrectM_KG3RwpPY40YPMpE8',
    appId: '1:133152571072:web:c5ba517685d5fa86237725',
    messagingSenderId: '133152571072',
    projectId: 'medialert-2024',
    authDomain: 'medialert-2024.firebaseapp.com',
    storageBucket: 'medialert-2024.firebasestorage.app',
  );

}